version: '3.4'

services:
  urlshortener.api:
    image: ${DOCKER_REGISTRY-}urlshortenerapi
    build:
      context: .
      dockerfile: UrlShortener.Api/Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=UrlShortenerDb;Username=postgres;Password=0902
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=UrlShortenerDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_v18:/var/lib/postgresql

volumes:
  postgres_data_v18: